WebApplication2/WebApplication2/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Business;
using BancoTiempoApp.Models;

namespace WebApplication2.Controllers
{
    public class SharedController : BaseController
    {
        // GET: Partial
        public ActionResult Index()
        {
            return View("Index","Home");
        }

        [ChildActionOnly]
        public ActionResult GetUserDisplay()
        {
            int userID = GetLoggedInUserId();
            GetUserDisplayModel mModel = new GetUserDisplayModel();
            mModel.Messages = MessageManager.GetNewMessages(userID);
            mModel.Chats = GroupManager.GetGroups(userID);
            foreach (var chat in mModel.Chats)
                chat.LastMessage = GroupManager.GetLastMessage(chat.chatGroupID);
            mModel.Chats = mModel.Chats.OrderBy(g => g.LastMessage.messageTimeSent).ToList();
            mModel.Time = UserManager.GetUser(userID).userTime;
            return View(mModel);
        }
    }
}

WebApplication2/WebApplication2/Views/Shared/GetUserDisplay.cshtml
@model BancoTiempoApp.Models.GetUserDisplayModel

@{
    ViewBag.Title = "GetNewMessages";
    Layout = null;
}

<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="badge" id="message-count">@Model.Messages.Count</span> Nous Missatges <span class="caret"></span></a>
    <ul class="dropdown-menu" id="new-messages">
        @foreach (var message in Model.Messages)
        {
            <li>@Html.ActionLink(message.messageFromUserName + ":" + message.messageBody, "ChatShow", "Chat", new { id = message.chatGroupID }, null) </li>
        }
    </ul>
</li>
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Els meus xats<span class="caret"></span></a>
    <ul class="dropdown-menu" id="my-chats">
        @foreach (var chatGroup in Model.Chats)
        {
            <li>@Html.ActionLink(chatGroup.offerOrDemandName + chatGroup.LastMessage.messageFromUserName + ":" + chatGroup.LastMessage.messageBody ,"ChatShow","Chat",new { id = chatGroup.chatGroupID },null)</li>
        }
    </ul>
</li>
<li> <a href="#">Tens @Model.Time h per gastar <span class="glyphicon glyphicon-time"></span></a> </li>

WebApplication2/WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/styles")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
</head>
<body style="background-color:#a7c4ff">
    <nav class="navbar navbar-default">
        <div class="container-fluid body-content">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Home/Index">
                    <img alt="Communitime" src="~/favicon.ico" style="width:30px;height:30px" />
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="/User/UserAccount/">El meu compte</a></li>
                    @{ Html.RenderAction("GetUserDisplay", "Shared"); }
                    <li><a href="/User/LogoutUser/">Surt</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>


    <div class="container body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
    @RenderSection("head", required: false)

</body>
</html>

WebApplication2/WebApplication2/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/styles")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="background-color:#99b8ff">
    
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)
</body>
</html>